language: R
cache:
  packages: true
  directories:
    - "$HOME/.cache/pip"
R:
  - 3.5
  - 3.6
  - release

os:
  - linux
arch:
  - x64
dist:
  - bionic

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
      - python-dev

before_install:
  - pip install --user numpy
  - pip install --user scipy
  - pip install --user --upgrade jax jaxlib

pandoc: false
latex: false

warnings_are_errors: false

notifications:
  email: false
